export const ALL_ADDRESSES_REQUEST = 'ALL_ADDRESSES_REQUEST'
export const ALL_ADDRESSES_SUCCESS = 'ALL_ADDRESSES_SUCCESS'
export const ALL_ADDRESSES_FAILURE = 'ALL_ADDRESSES_FAILURE'

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE'
export const CREATE_ADDRESS_RESET = 'CREATE_ADDRESS_RESET'

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE'
export const UPDATE_ADDRESS_RESET = 'UPDATE_ADDRESS_RESET'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE'
export const DELETE_ADDRESS_RESET = 'DELETE_ADDRESS_RESET'

export const ALL_COUNTRIES_REQUEST = 'ALL_COUNTRIES_REQUEST'
export const ALL_COUNTRIES_SUCCESS = 'ALL_COUNTRIES_SUCCESS'
export const ALL_COUNTRIES_FAILURE = 'ALL_COUNTRIES_FAILURE'

export const ALL_STATES_REQUEST = 'ALL_STATES_REQUEST'
export const ALL_STATES_SUCCESS = 'ALL_STATES_SUCCESS'
export const ALL_STATES_FAILURE = 'ALL_STATES_FAILURE'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'